name: CI - Test wordle Utility

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build playtest
        run: make playtest

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: playtest	
          path: ./playtest
    
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: Run Tests		
        run:  make playtest; ./test_script >test_results.txt; gcov playtest-words.c; gcov playtest-checkWord.c; gcov playtest-checkletter.c; gcov playtest-chooseWord.c
      - name: Upload Test Results
        if: ${{ always() }}
      
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results		
          path: ./test_results.txt

      - name: Upload Test Results 1
        if: ${{ always() }}
        
        uses: actions/upload-artifact@v4	
        with:
          name: gcov words.c
          path: ./words.c.gcov

      - name: Upload Test Results	2		
        if: ${{ always() }}
      
        uses: actions/upload-artifact@v4	
        with:
          name: gcov checkletter.c
          path: ./checkletter.c.gcov
          
      - name: Upload Test Results	3		
        if: ${{ always() }}
      
        uses: actions/upload-artifact@v4	
        with:
          name: gcov checkWord.c
          path: ./checkWord.c.gcov
          
      - name: Upload Test Results	4
        if: ${{ always() }}
      
        uses: actions/upload-artifact@v4	
        with:
          name: gcov chooseWord.c	
          path: ./chooseWord.c.gcov
