name: CI - Test wordle Utility

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build playtest
        run: make playtest

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: playtest	
          path: ./playtest
    
  test:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: Run Tests		
        run:  make playtest; ./test_script >test_results.txt; gcov playtest-playWords.c
      - name: Upload Test Results
        if: ${{ always() }}
      
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results		
          path: ./test_results.txt

      - name: Upload Test Results 1
        if: ${{ always() }}
        
        uses: actions/upload-artifact@v4	
        with:
          name: gcov playWords.c
          path: ./playWords.c.gcov
